### PR TITLE
Supply id and growth user info for workshop

### PR DESCRIPTION
**Pull request by bmneely**

### CODE REVIEW

**Comment by bmneely** [comment]
For context https://github.com/Bloc/workshop/issues/488

**Comment by mikesjewett** [comment]
@dpaola2 @mmarquardt610 any reason why we can't merge this? It's part of a few issues that are currently blocking Workshop as a growth product.

**Comment by mmarquardt610** [comment]
I haven't had a chance to look at this, I'll be able to spend some time looking at this and D3040 this morning. Sorry for the delay.

**Comment by dpaola2** [comment]
FWIW you are free to tag other engineers as well. Your likelihood of being reviewed quickly goes up drastically. We don't look at this repo often at all, as all our dev process lives in phabricator.

**Comment by mmarquardt610** [comment]
brett's going to take my place on reviewing this, thanks!!

**Comment by brettjanderson** [comment]
Merged.

**Pull request merged**
